-- initial schema for datasets, runs, predictions
-- IDs are text, generated by app (crypto.randomUUID)
-- Safe defaults to avoid extension dependencies.

create table if not exists datasets (
  id text primary key,
  name text not null,
  csv_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists training_runs (
  id text primary key,
  dataset_id text not null references datasets(id) on delete cascade,
  status text not null default 'created', -- created | running | completed | failed
  notes text,
  metrics jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists predictions (
  id bigserial primary key,
  run_id text not null references training_runs(id) on delete cascade,
  protein_a text not null,
  protein_b text not null,
  probability double precision,
  drug_targets_overlap boolean,
  created_at timestamptz not null default now()
);
